# Tadka - Docker Compose
# Day 1 & Day 2: PostgreSQL + Java Spring Boot API

services:
  postgres:
    image: postgres:16
    container_name: tadka-postgres
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tadka}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tadka_local}
      POSTGRES_DB: ${POSTGRES_DB:-tadka}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tadka"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tadka-redis
    ports:
      - "6379:6379"
    restart: unless-stopped


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tadka-api
    ports:
      - "5224:5224"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tadka
      SPRING_DATASOURCE_USERNAME: tadka
      SPRING_DATASOURCE_PASSWORD: tadka_local
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
